== LISTA DE REQUISITOS INICIAL V2

REGISTRO DE USUARIO

* REG.1 El sistema permitirá al usuario no registrado crear una cuenta de usuario en el sistema IRBET proporcionando sus datos personales: 

** REG.1.1 DNI/NIF o NIE

** REG.1.2 Nombre 

** REG.1.3 Apellidos 

** REG.1.4 Correo Electrónico 

** REG.1.5 Contraseña. 

** REG.1.6 Confirmación de la contraseña

** REG.1.7 Dirección de domicilio

** REG.1.8 Fecha de nacimiento

** REG.1.9 Género
*** REG.1.9.1 Hombre
*** REG.1.9.2 Mujer
*** REG.1.9.3 Otro

** REG.1.10 Pregunta de seguridad

** REG.1.11 Respuesta secreta a la pregunta de seguridad

** REG.1.12 Elegir punto de venta presencial:
*** REG.1.12.1 Identificador de 5 cifras 

** REG.1.13 Servicios de los que quiere disponer:
*** REG.1.13.1 Comunicación de próximos sorteos
*** REG.1.13.2 Información comercial sobre nuevos productos
*** REG.1.13.3 Encuestas por correo electrónico
*** REG.1.13.4 Comunicaciones de los próximos sorteos
*** REG.1.13.5 Información comercial sobre nuevos productos

** REG.1.14 El sistema completará el proceso de alta de usuario:
*** REG.1.14.1 Dadas las condiciones:
**** REG.1.14.1.1 Los datos de registro introducidos sean correctos
**** REG.1.14.1.2 El usuario no exista en la base de datos
*** REG.1.14.2 El sistema tras comprobar que los datos correctos se procederá al proceso de autenticación, AUT.1.

* REG.2 El sistema no permitira el registro de un usuario que haya rellenado los datos relativos a RF.1 si:
** REG.2.1 El usuario que se intenta registrar forma parte de la lista negra de jugadores con ludopatia.
** REG.2.2 El usuario tiene menos de 18 años.


AUTENTICACIÓN

* AUT.1. El usuario registrado no autenticado podrá iniciar sesión en el sistema con sus credenciales de usuario: 

** AUT.1.1 Correo electrónico. 

** AUT.1.2 Contraseña. 

** AUT.1.3 El sistema completará el proceso de inicio de sesión una vez comprobado que los datos proporcionados coincidan con los datos de registro REG.1 .

FUNCIONES DE USUARIO ANONIMO

* UANO.1 El sistema permitirá al usuario sin cuenta realizar las siguientes funciones(usuario anónimo):
** UANO.1.1 Ver las estadiísticas de sorteos pasados.
** UANO.1.2 Si dispone de cuenta usuario, podrá iniciar sesión.
** UANO.1.3 Podrá consultar los resultados:
*** UANO.1.3.1 Los resultados del último sorteo.
*** UANO.1.3.2 Los resultados en un intervalo de tiempo especificado.

* UANO.2 El sistema no permitirá al usuario sin cuenta realizar las siguientes funciones(usuario anónimo):
** UANO.2.1 El usuario anónimo no podrá realizar ningún tipo de apuesta.
** UANO.2.2 El usuario anónimo no registrado podrá registrarse.



FUNCIONES DE USUARIO AUTENTICADO

* UAUT.1 El usuario registrado podrá configurar los datos de su perfil: 

** UAUT.1.1 Teléfono. 

** UAUT.1.2 Correo electrónico. 

** UAUT.1.3 Método de pago. 

** UAUT.1.4 Género.

** UAUT.1.5 Dirección de domicilio.

** UAUT.1.6 Residencia fiscal.

** UAUT.1.7 Idioma preferente.

** UAUT.1.8 Pregunta de seguridad.

** UAUT.1.9 Respuesta a la pregunta de seguridad.

** UAUT.1.10 Contraseña

* UAUT.2 El usuario autenticado podrá comprobar el historial de resultados de sorteos pasados:
** UAUT.2.1 Cada resultado muestra la fecha del sorteo.
** UAUT.2.2 Cada resultado muestra el reintegro del sorteo.
** UAUT.2.3 Cada resultado muestra el número complementario del sorteo.
** UAUT.2.4 Cada resultado muestra los siguientes datos relacionados al joker:
** UAUT.2.4.1 El número del joker.
** UAUT.2.4.2 Las categorías del joker.
** UAUT.2.5 Cada resultado muestra las estadísticas del sorteo.
** UAUT.2.6 Cada resultado muestra la recaudación total del sorteo.

* UAUT.3 El usuario autenticado podrá darse de baja, eliminando su cuenta de usuario del sistema IRBET. 

* UAUT.4 El usuario autenticado podrá consultar en relación a sus apuestas:
** UAUT.4.1 Si sus apuestas son ganadoras.
** UAUT.4.2 Si son ganadoras, el importe del premio.
** UAUT.4.3 Los datos del sorteo especificados en UAUT.2. 

* UAUT.5 El usuario podrá escoger una de las diferentes apuestas disponibles para ser rellenadas: 
** UAUT.5.1 Sorteo semanal.
** UAUT 5.2 Sorteo diario.

* UAUT.6 El sistema deberá al usuario rellenar la apuesta seleccionada en UAUT.5:
** UAUT.6.1 El sistema permitirá realizar apuestas de forma similar a las hechas en un punto de venta físico:
*** UAUT.6.1.1 El sistema permitirá apuestas simples:
**** UAUT.6.1.1.1 Se podrán realizar hasta 8 apuestas.
**** UAUT.6.1.1.2 Se podrán elegir hasta 6 números por apuesta.
**** UAUT.6.1.1.3 Se podrá añadir un reintegro a la apuesta.
**** UAUT.6.1.1.4 Se permitirá la rellenar la apuesta con número generados de forma aleatoria.
*** UAUT.6.1.2 El sistema permitirá apuestas compuestas:
**** UAUT.6.1.2.1 Se podrán realizar hasta 1 apuestas.
**** UAUT.6.1.2.2 Se podrán elegir hasta 5 números por apuesta, hasta un máximo de 11.
**** UAUT.6.1.2.3 Se podrá añadir un reintegro a la apuesta.
**** UAUT.6.1.2.4 Se permitirá la rellenar la apuesta con número generados de forma aleatoria de forma similar a UAUT.6.1.4 .
** UAUT.6.2 El sistema ofrecerá la posibilidad de añadir un Joker a la apuesta por PRECIO_JOKER euros. 


GESTION DE APUESTAS

* RGA.1 El Sistema deberá generar un resguardo tras la compra de un boleto, con el mismo formato que los resguardos obtenidos de puntos de venta físicos e incluyendo los siguientes datos:
** RGA.1.1 El resguardo digital deberá mostrar el logo del sorteo.
** RGA.1.2 El resguardo digital deberá mostrar la combinación seleccionada por el usuario.
** RGA.1.3 El resguardo digital deberá mostrar el valor del reintegro.
** RGA.1.4 El resguardo digital deberá mostrar el valor de la apuesta.
** RGA.1.5 El resguardo digital deberá mostrar la fecha de compra del boleto. 

* RGA.2 El sistema notificará a los ganadores del sorteo:
** RGA.2.1 Si el usuario tiene su teléfono registrado, a través de SMS.
** RGA2.2 En caso de que no se cumpla RGA2.1, a través de correo electrónico.

* RGA.3 El sistema deberá de utulizar los fondos del monedero para las transacciones relacionadas a las apuestas: 
** RGA.3.1 Si el usuario no dispone de fondos se notificará al usuario a través de sus métodos de contacto.
** RGA.3.2 Si el usuario dispone de fondos se procederá al juego.

* RGA.4. El usuario podrá solicitar un resguado para imprimir de los sorteos en los que participe, ó haya participado en un plazo de 20 días después del sorteo. 


* RGA.5 El sistema deberá de ingresar la cuantía de los premios a los ganadores del sorteo en:
** RGA.5.1 El monedero virtual (LOTOBOLSA) del usuario si la cantidad es menor a CUANTIA_MIN_BANCO euros.
** RGA.5.2 La cuenta bancaria del usuario si la cantidad es mayor a CUANTIA_MIN_BANCO euros y menor de CUANTIA_MAX_BANCO euros.


GESTION DE MONEDERO


* RGM.1 : El sistema permitirá al usuario ingresar dinero en su monedero digital (Lotobolsa) de IRBET mediante: 
** RGM.1.1 Tarjetas de crédito/débito.
** RGM.1.2 Pasarelas de pago: 
*** RGM.1.2.1 PayPal. 

* RGM.2 : El sistema permitirá al usuario consultar el valor de su monedero.

* RGM.3 : El sistema permitirá al usuario retirar sus fondos del monedero: 
** RGM.3.1 : El sistema deberá de comprobar que el usuario tenga fondos en su monedero.

LISTA NO FUNCIONALES

INTERFACES DE USUARIO

RUI.1

HARDWARE

RHW.1 //base de datos

COMUNICACION EXTERIOR

* RCOM.1 El sistema se comunicará con el servidor de hosting.

* RCOM.2 El sistema se comunicará con el servidor de dominio.

* RCOM.3 El sistema se comunicará con APIs: 
** RCOM.3.1 GoogleMaps API, para la localización de puntos físicos.
** RCOM.3.2 Gmail API, para enviar correos desde a los usuarios.
** RCOM.3.3 Google Analytics, para la recopilación de estadísticas y cookies.
** RCOM.3.4 El sistema dispondrá de un acceso directo a redes sociales: 
*** RCOM.3.4.1 Twitter.
*** RCOM.3.4.2 Facebook.
*** RCOM.3.4.3 Youtube.



NORMATIVAS Y LEYES

* RNORM.1 El sitio Web se debe ajustar a las normas establecidas por la LSSICE, Ley 34/2002 

** RNORM.1.1 Se incluirá un Aviso Legal, en el que se incluirán los datos básicos del negocio (Artículo 10) 

*** RNORM.1.1.1 Propietario del sitio (nombre o denominación social). 

*** RNORM.1.1.2 Datos de contacto: domicilio, dirección de correo electrónico, teléfono o número de fax. 

*** RNORM.1.1.3 Número de Identificación Fiscal. 

*** RNORM.1.1.4 Si está registrado en el Registro mercantil indicar el número de tomo, libro, folio y hoja. 

*** RNORM.1.1.5 Si se encuentra registrado en otro registro distinto público del Registro Mercantil, indicar el número de inscripción que le corresponda 

*** RNORM.1.1.6 Si necesita una autorización administrativa previa, incluir los datos de la autorización y el órgano competente encargado de la supervisión. 

*** RNORM.1.1.7 Si se encuentra adherido a algún código de conducta, indicarlo y facilitar el acceso de forma electrónica a dicho código de conducta. 

*** RNORM.1.1.8 Si ejerce una actividad regulada, deberá indicar: 

**** RNORM.1.1.8.1 Datos del Colegio profesional y número de colegiado. 

**** RNORM.1.1.8.2 Título académico oficial o profesional. 

**** RNORM.1.1.8.3 Dónde se expidió y si procede, su homologación. 

**** RNORM.1.1.8.4 Normas profesionales que debe seguir, indicando cómo poder acceder a dicha información. 

** RNORM.1.2 Se debe facilitar a cualquier usuario el acceso al Aviso Legal (Artículo 10) 

** RNORM.1.3 Si el negocio vende artículos, deberá informar sobre (Artículo 10):  

*** RNORM.1.3.1 El precio de los productos, indicando si se incluye o no los impuestos. 

*** RNORM.1.3.2 Los gastos de envío, en el caso de que los haya. 

*** RNORM.1.3.3 Los plazos y políticas de entrega. 







= Futura tabla
 CUANTIA_MIN_BANCO -> 2000
 CUANTIA_MAX_BANCO -> 40000

